import type { Bag } from "@/types";

export const BAGS: Bag[] = [
  {
    id: "b1",
    name: "Mosaico joya",
    color: ["multicolor"],
    colorHex: "linear-gradient(140deg, #C45A7A, #454170, #5B9880, #006C88)",
    imageUrl: "/images/Bolsas/1.webp",
    isAvailable: true,
    imageScale: 1.25,
    imageOffsetY: 0,
  },
  {
    id: "b2",
    name: "Concha champagne",
    color: ["champagne"],
    colorHex: "#E8D5B5",
    imageUrl: "/images/Bolsas/2.webp",
    isAvailable: true,
    imageScale: 1.48,
    imageOffsetY: 0,
  },
  {
    id: "b3",
    name: "Rosa cristal",
    color: ["rosa"],
    colorHex: "#E8A0B0",
    imageUrl: "/images/Bolsas/3.webp",
    isAvailable: true,
    imageScale: 1.48,
    imageOffsetY: 0,
  },
  {
    id: "b4",
    name: "Rosa plisado",
    color: ["rosa"],
    colorHex: "#E8C4C4",
    imageUrl: "/images/Bolsas/4.webp",
    isAvailable: true,
    imageScale: 1.48,
    imageOffsetY: 7,
  },
  {
    id: "b5",
    name: "Rosa brillante",
    color: ["rosa"],
    colorHex: "#E5B4C0",
    imageUrl: "/images/Bolsas/5.webp",
    isAvailable: true,
    imageScale: 1.44,
    imageOffsetY: -20,
  },
  {
    id: "b6",
    name: "Oro rosa metalizado",
    color: ["rosa"],
    colorHex: "#CB9D76",
    imageUrl: "/images/Bolsas/6.webp",
    isAvailable: true,
    imageScale: 1.44,
    imageOffsetY: 5,
  },
  {
    id: "b7",
    name: "Negro joya",
    color: ["negro"],
    colorHex: "#1A1A1A",
    imageUrl: "/images/Bolsas/7.webp",
    isAvailable: true,
    imageScale: 1.45,
    imageOffsetY: 10,
  },
  {
    id: "b8",
    name: "Plata brillante",
    color: ["plata"],
    colorHex: "#C0C0C0",
    imageUrl: "/images/Bolsas/8.webp",
    isAvailable: true,
    imageScale: 1.48,
    imageOffsetY: -25,
  },
  {
    id: "b9",
    name: "Negro cristal",
    color: ["negro"],
    colorHex: "#111111",
    imageUrl: "/images/Bolsas/9.webp",
    isAvailable: true,
    imageScale: 1.48,
    imageOffsetY: 0,
  },
  {
    id: "b10",
    name: "Oro rosa",
    color: ["oro rosa"],
    colorHex: "#B76E79",
    imageUrl: "/images/Bolsas/10.webp",
    isAvailable: true,
    imageScale: 1.48,
    imageOffsetY: 0,
  },
  {
    id: "b11",
    name: "Negro floral",
    color: ["negro"],
    colorHex: "#1A1A1A",
    imageUrl: "/images/Bolsas/11.webp",
    isAvailable: true,
    imageScale: 1.48,
    imageOffsetY: -10,
  },
  {
    id: "b12",
    name: "Plata floral",
    color: ["plata"],
    colorHex: "#D4D4D8",
    imageUrl: "/images/Bolsas/12.webp",
    isAvailable: true,
    imageScale: 1.48,
    imageOffsetY: 0,
  },
  {
    id: "b13",
    name: "Oro nudo",
    color: ["dorado"],
    colorHex: "#D4A017",
    imageUrl: "/images/Bolsas/13.webp",
    isAvailable: true,
    imageScale: 1.48,
    imageOffsetY: 10,
  },
  {
    id: "b14",
    name: "Rafia natural",
    color: ["beige"],
    colorHex: "#B48D65",
    imageUrl: "/images/Bolsas/14.webp",
    isAvailable: true,
    imageScale: 1.48,
    imageOffsetY: -20,
  },
  {
    id: "b15",
    name: "Clutch magenta",
    color: ["rosa"],
    colorHex: "#CD437D",
    imageUrl: "/images/Bolsas/15.webp",
    isAvailable: true,
    imageScale: 1.48,
    imageOffsetY: -20,
  },
  {
    id: "b16",
    name: "Bolso arena",
    color: ["café"],
    colorHex: "#D3BBA8",
    imageUrl: "/images/Bolsas/16.webp",
    isAvailable: true,
    imageScale: 1.48,
    imageOffsetY: -20,
  },
];
