import { DressCategory, ServiceIcon } from "@/types";

import type { Dress, ProcessStep, Service } from "@/types";

export const SERVICES: Service[] = [
  {
    title: "Renta de vestidos",
    description:
      "Diseños inolvidables para tu evento, sin comprometer tu presupuesto.",
    icon: ServiceIcon.SPARKLES,
  },
  {
    title: "Venta de vestidos",
    description:
      "Encuentra esa pieza especial que querrás conservar para siempre.",
    icon: ServiceIcon.SHOPPING_BAG,
  },
  {
    title: "Asesoría personalizada",
    description:
      "Te ayudamos a elegir el corte, color y talla que mejor realzan tu estilo.",
    icon: ServiceIcon.HEART_HANDSHAKE,
  },
];

export const PROCESS_STEPS: ProcessStep[] = [
  {
    number: "01",
    title: "Elige tu vestido",
    description: "Explora nuestros estilos y guarda tus favoritos.",
  },
  {
    number: "02",
    title: "Escríbenos",
    description: "Confirma disponibilidad y recibe asesoría por WhatsApp.",
  },
  {
    number: "03",
    title: "Aparta tu fecha",
    description: "Agenda tu prueba y asegura el vestido para tu evento.",
  },
  {
    number: "04",
    title: "Luce espectacular",
    description: "Recibe tu vestido listo para hacer de tu noche algo único.",
  },
];

export const DRESSES: Dress[] = [
  {
    id: "rojo",
    name: "Rojo intenso",
    price: 850,
    sizes: [],
    color: "rojo",
    colorHex: "#D01B30",
    imageUrl: "/images/dresses/1.webp",
    category: DressCategory.EVENING,
    isAvailable: true,
  },
  {
    id: "oro-rosa",
    name: "Oro rosa",
    price: 850,
    sizes: [],
    color: "rosa",
    colorHex: "#EFDCDE",
    imageUrl: "/images/dresses/2.webp",
    category: DressCategory.GRADUATION,
    isAvailable: true,
  },
  {
    id: "negro-cuero",
    name: "Negro cuero",
    price: 850,
    sizes: [],
    color: "negro",
    colorHex: "#201E1A",
    imageUrl: "/images/dresses/3.webp",
    category: DressCategory.QUINCEANERA,
    isAvailable: true,
  },
  {
    id: "purpura-bizantino",
    name: "Púrpura bizantino",
    price: 850,
    sizes: ["CH"],
    color: "púrpura",
    colorHex: "#9F3383",
    imageUrl: "/images/dresses/4.webp",
    category: DressCategory.EVENING,
    isAvailable: true,
    imageScale: 1.13,
  },
  {
    id: "azul-crepusculo",
    name: "Azul Crepúsculo",
    price: 850,
    sizes: ["CH", "G"],
    color: "azul",
    colorHex: "#102F3D",
    imageUrl: "/images/dresses/5.webp",
    category: DressCategory.WEDDING,
    isAvailable: true,
    imageScale: 1.25,
  },
  {
    id: "cuarzo-rosa",
    name: "Cuarzo rosa",
    price: 850,
    sizes: ["XS", "XG"],
    color: "rosa",
    colorHex: "#F3C9C3",
    imageUrl: "/images/dresses/6.webp",
    category: DressCategory.GRADUATION,
    isAvailable: true,
    imageScale: 1.11,
  },
  {
    id: "negro-obsidiana",
    name: "Negro obsidiana",
    price: 950,
    sizes: ["CH", "M"],
    color: "negro",
    colorHex: "#0E0D12",
    imageUrl: "/images/dresses/7.webp",
    category: DressCategory.EVENING,
    isAvailable: true,
    imageScale: 1.1,
  },
  {
    id: "azul-petroleo",
    name: "Azul petróleo",
    price: 0,
    sizes: ["G", "XG"],
    color: "azul cielo",
    colorHex: "#045D90",
    imageUrl: "/images/dresses/8.webp",
    category: DressCategory.WEDDING,
    isAvailable: true,
    imageScale: 1.08,
  },
  {
    id: "rojo-fresa",
    name: "Rojo fresa",
    price: 850,
    sizes: ["M"],
    color: "rojo",
    colorHex: "#FB2B3D",
    imageUrl: "/images/dresses/9.webp",
    category: DressCategory.QUINCEANERA,
    isAvailable: true,
    imageScale: 1.18,
  },
  {
    id: "negro",
    name: "Negro",
    price: 780,
    sizes: ["M"],
    color: "negro",
    colorHex: "#272429",
    imageUrl: "/images/dresses/10.webp",
    category: DressCategory.EVENING,
    isAvailable: true,
    imageScale: 1.13,
  },
  {
    id: "lila-grisaceo",
    name: "Lila grisáceo",
    price: 700,
    sizes: ["XS"],
    color: "gris",
    colorHex: "#ACABBF",
    imageUrl: "/images/dresses/11.webp",
    category: DressCategory.GRADUATION,
    isAvailable: true,
    imageScale: 1.12,
  },
  {
    id: "floral-multicolor",
    name: "Floral multicolor",
    price: 1350,
    sizes: ["M"],
    color: "varios",
    colorHex:
      "linear-gradient(135deg, #BA9248, #EEDBD1, #006C88, #C85071, #70369D)",
    imageUrl: "/images/dresses/12.webp",
    category: DressCategory.WEDDING,
    isAvailable: true,
    imageScale: 1.11,
  },
  {
    id: "fucsia",
    name: "Fucsia",
    price: 900,
    sizes: ["M"],
    color: "rosa",
    colorHex: "#F03595",
    imageUrl: "/images/dresses/13.webp",
    category: DressCategory.EVENING,
    isAvailable: true,
    imageScale: 1.11,
  },
  {
    id: "rojo-1",
    name: "Pendiente",
    price: 900,
    sizes: ["M"],
    color: "rosa",
    colorHex: "#F03595",
    imageUrl: "/images/dresses/14.webp",
    category: DressCategory.EVENING,
    isAvailable: true,
    imageScale: 1.23,
  },
  {
    id: "rojo-1",
    name: "Pendiente",
    price: 900,
    sizes: ["M"],
    color: "rosa",
    colorHex: "#F03595",
    imageUrl: "/images/dresses/15.webp",
    category: DressCategory.EVENING,
    isAvailable: true,
    imageScale: 1.23,
  },
  {
    id: "rojo-1",
    name: "Pendiente",
    price: 900,
    sizes: ["M"],
    color: "rosa",
    colorHex: "#F03595",
    imageUrl: "/images/dresses/16.webp",
    category: DressCategory.EVENING,
    isAvailable: true,
    imageScale: 1.23,
  },
  {
    id: "rojo-1",
    name: "Pendiente",
    price: 900,
    sizes: ["M"],
    color: "rosa",
    colorHex: "#F03595",
    imageUrl: "/images/dresses/17.webp",
    category: DressCategory.EVENING,
    isAvailable: true,
    imageScale: 1.23,
  },
  {
    id: "rojo-1",
    name: "Pendiente",
    price: 900,
    sizes: ["M"],
    color: "rosa",
    colorHex: "#F03595",
    imageUrl: "/images/dresses/18.webp",
    category: DressCategory.EVENING,
    isAvailable: true,
    imageScale: 1.23,
  },
  {
    id: "rojo-1",
    name: "Pendiente",
    price: 900,
    sizes: ["M"],
    color: "rosa",
    colorHex: "#F03595",
    imageUrl: "/images/dresses/19.webp",
    category: DressCategory.EVENING,
    isAvailable: true,
    imageScale: 1.23,
  },
  {
    id: "rojo-1",
    name: "Pendiente",
    price: 900,
    sizes: ["M"],
    color: "rosa",
    colorHex: "#F03595",
    imageUrl: "/images/dresses/20.webp",
    category: DressCategory.EVENING,
    isAvailable: true,
    imageScale: 1.23,
  },
  {
    id: "rojo-1",
    name: "Pendiente",
    price: 900,
    sizes: ["M"],
    color: "rosa",
    colorHex: "#F03595",
    imageUrl: "/images/dresses/21.webp",
    category: DressCategory.EVENING,
    isAvailable: true,
    imageScale: 1.23,
  },
  {
    id: "rojo-1",
    name: "Pendiente",
    price: 900,
    sizes: ["M"],
    color: "rosa",
    colorHex: "#F03595",
    imageUrl: "/images/dresses/22.webp",
    category: DressCategory.EVENING,
    isAvailable: true,
    imageScale: 1.23,
  },
  {
    id: "rojo-1",
    name: "Pendiente",
    price: 900,
    sizes: ["M"],
    color: "rosa",
    colorHex: "#F03595",
    imageUrl: "/images/dresses/23.webp",
    category: DressCategory.EVENING,
    isAvailable: true,
    imageScale: 1.23,
  },
  {
    id: "rojo-1",
    name: "Pendiente",
    price: 900,
    sizes: ["M"],
    color: "rosa",
    colorHex: "#F03595",
    imageUrl: "/images/dresses/24.webp",
    category: DressCategory.EVENING,
    isAvailable: true,
    imageScale: 1.23,
  },
  {
    id: "rojo-1",
    name: "Pendiente",
    price: 900,
    sizes: ["M"],
    color: "rosa",
    colorHex: "#F03595",
    imageUrl: "/images/dresses/25.webp",
    category: DressCategory.EVENING,
    isAvailable: true,
    imageScale: 1.23,
  },
  {
    id: "rojo-1",
    name: "Pendiente",
    price: 900,
    sizes: ["M"],
    color: "rosa",
    colorHex: "#F03595",
    imageUrl: "/images/dresses/26.webp",
    category: DressCategory.EVENING,
    isAvailable: true,
    imageScale: 1.23,
  },
  {
    id: "rojo-1",
    name: "Pendiente",
    price: 900,
    sizes: ["M"],
    color: "rosa",
    colorHex: "#F03595",
    imageUrl: "/images/dresses/27.webp",
    category: DressCategory.EVENING,
    isAvailable: true,
    imageScale: 1.23,
  },
  {
    id: "rojo-1",
    name: "Pendiente",
    price: 900,
    sizes: ["M"],
    color: "rosa",
    colorHex: "#F03595",
    imageUrl: "/images/dresses/28.webp",
    category: DressCategory.EVENING,
    isAvailable: true,
    imageScale: 1.23,
  },
  {
    id: "rojo-1",
    name: "Pendiente",
    price: 900,
    sizes: ["M"],
    color: "rosa",
    colorHex: "#F03595",
    imageUrl: "/images/dresses/29.webp",
    category: DressCategory.EVENING,
    isAvailable: true,
    imageScale: 1.23,
  },
  {
    id: "rojo-1",
    name: "Pendiente",
    price: 900,
    sizes: ["M"],
    color: "rosa",
    colorHex: "#F03595",
    imageUrl: "/images/dresses/30.webp",
    category: DressCategory.EVENING,
    isAvailable: true,
    imageScale: 1.23,
  },
  {
    id: "rojo-1",
    name: "Pendiente",
    price: 900,
    sizes: ["M"],
    color: "rosa",
    colorHex: "#F03595",
    imageUrl: "/images/dresses/31.webp",
    category: DressCategory.EVENING,
    isAvailable: true,
    imageScale: 1.23,
  },
  {
    id: "rojo-1",
    name: "Pendiente",
    price: 900,
    sizes: ["M"],
    color: "rosa",
    colorHex: "#F03595",
    imageUrl: "/images/dresses/32.webp",
    category: DressCategory.EVENING,
    isAvailable: true,
    imageScale: 1.23,
  },
  {
    id: "rojo-1",
    name: "Pendiente",
    price: 900,
    sizes: ["M"],
    color: "rosa",
    colorHex: "#F03595",
    imageUrl: "/images/dresses/33.webp",
    category: DressCategory.EVENING,
    isAvailable: true,
    imageScale: 1.23,
  },
  {
    id: "rojo-1",
    name: "Pendiente",
    price: 900,
    sizes: ["M"],
    color: "rosa",
    colorHex: "#F03595",
    imageUrl: "/images/dresses/34.webp",
    category: DressCategory.EVENING,
    isAvailable: true,
    imageScale: 1.23,
  },
  {
    id: "rojo-1",
    name: "Pendiente",
    price: 900,
    sizes: ["M"],
    color: "rosa",
    colorHex: "#F03595",
    imageUrl: "/images/dresses/35.webp",
    category: DressCategory.EVENING,
    isAvailable: true,
    imageScale: 1.23,
  },
  {
    id: "rojo-1",
    name: "Pendiente",
    price: 900,
    sizes: ["M"],
    color: "rosa",
    colorHex: "#F03595",
    imageUrl: "/images/dresses/36.webp",
    category: DressCategory.EVENING,
    isAvailable: true,
    imageScale: 1.23,
  },
  {
    id: "rojo-1",
    name: "Pendiente",
    price: 900,
    sizes: ["M"],
    color: "rosa",
    colorHex: "#F03595",
    imageUrl: "/images/dresses/37.webp",
    category: DressCategory.EVENING,
    isAvailable: true,
    imageScale: 1.23,
  },
  {
    id: "rojo-1",
    name: "Pendiente",
    price: 900,
    sizes: ["M"],
    color: "rosa",
    colorHex: "#F03595",
    imageUrl: "/images/dresses/38.webp",
    category: DressCategory.EVENING,
    isAvailable: true,
    imageScale: 1.23,
  },
  {
    id: "rojo-1",
    name: "Pendiente",
    price: 900,
    sizes: ["M"],
    color: "rosa",
    colorHex: "#F03595",
    imageUrl: "/images/dresses/39.webp",
    category: DressCategory.EVENING,
    isAvailable: true,
    imageScale: 1.23,
  },
  {
    id: "rojo-1",
    name: "Pendiente",
    price: 900,
    sizes: ["M"],
    color: "rosa",
    colorHex: "#F03595",
    imageUrl: "/images/dresses/40.webp",
    category: DressCategory.EVENING,
    isAvailable: true,
    imageScale: 1.23,
  },
  {
    id: "rojo-1",
    name: "Pendiente",
    price: 900,
    sizes: ["M"],
    color: "rosa",
    colorHex: "#F03595",
    imageUrl: "/images/dresses/41.webp",
    category: DressCategory.EVENING,
    isAvailable: true,
    imageScale: 1.23,
  },
  {
    id: "rojo-1",
    name: "Pendiente",
    price: 900,
    sizes: ["M"],
    color: "rosa",
    colorHex: "#F03595",
    imageUrl: "/images/dresses/42.webp",
    category: DressCategory.EVENING,
    isAvailable: true,
    imageScale: 1.23,
  },
  {
    id: "rojo-1",
    name: "Pendiente",
    price: 900,
    sizes: ["M"],
    color: "rosa",
    colorHex: "#F03595",
    imageUrl: "/images/dresses/43.webp",
    category: DressCategory.EVENING,
    isAvailable: true,
    imageScale: 1.23,
  },
  {
    id: "rojo-1",
    name: "Pendiente",
    price: 900,
    sizes: ["M"],
    color: "rosa",
    colorHex: "#F03595",
    imageUrl: "/images/dresses/44.webp",
    category: DressCategory.EVENING,
    isAvailable: true,
    imageScale: 1.23,
  },
  {
    id: "rojo-1",
    name: "Pendiente",
    price: 900,
    sizes: ["M"],
    color: "rosa",
    colorHex: "#F03595",
    imageUrl: "/images/dresses/45.webp",
    category: DressCategory.EVENING,
    isAvailable: true,
    imageScale: 1.23,
  },
  {
    id: "rojo-1",
    name: "Pendiente",
    price: 900,
    sizes: ["M"],
    color: "rosa",
    colorHex: "#F03595",
    imageUrl: "/images/dresses/46.webp",
    category: DressCategory.EVENING,
    isAvailable: true,
    imageScale: 1.23,
  },
  {
    id: "rojo-1",
    name: "Pendiente",
    price: 900,
    sizes: ["M"],
    color: "rosa",
    colorHex: "#F03595",
    imageUrl: "/images/dresses/47.webp",
    category: DressCategory.EVENING,
    isAvailable: true,
    imageScale: 1.23,
  },
  {
    id: "rojo-1",
    name: "Pendiente",
    price: 900,
    sizes: ["M"],
    color: "rosa",
    colorHex: "#F03595",
    imageUrl: "/images/dresses/48.webp",
    category: DressCategory.EVENING,
    isAvailable: true,
    imageScale: 1.23,
  },
  {
    id: "rojo-1",
    name: "Pendiente",
    price: 900,
    sizes: ["M"],
    color: "rosa",
    colorHex: "#F03595",
    imageUrl: "/images/dresses/49.webp",
    category: DressCategory.EVENING,
    isAvailable: true,
    imageScale: 1.23,
  },
  {
    id: "rojo-1",
    name: "Pendiente",
    price: 900,
    sizes: ["M"],
    color: "rosa",
    colorHex: "#F03595",
    imageUrl: "/images/dresses/50.webp",
    category: DressCategory.EVENING,
    isAvailable: true,
    imageScale: 1.23,
  },
];
