import { DressCategory, ServiceIcon } from "@/types";
import type { Dress, ProcessStep, Service } from "@/types";

export const SERVICES: Service[] = [
  {
    title: "Renta de vestidos",
    description:
      "Diseños inolvidables para tu evento, sin comprometer tu presupuesto.",
    icon: ServiceIcon.SPARKLES,
  },
  {
    title: "Venta de vestidos",
    description:
      "Encuentra esa pieza especial que querrás conservar para siempre.",
    icon: ServiceIcon.SHOPPING_BAG,
  },
  {
    title: "Asesoría personalizada",
    description:
      "Te ayudamos a elegir el corte, color y talla que mejor realzan tu estilo.",
    icon: ServiceIcon.HEART_HANDSHAKE,
  },
];

export const PROCESS_STEPS: ProcessStep[] = [
  {
    number: "01",
    title: "Elige tu vestido",
    description: "Explora nuestros estilos y guarda tus favoritos.",
  },
  {
    number: "02",
    title: "Escríbenos",
    description: "Confirma disponibilidad y recibe asesoría por WhatsApp.",
  },
  {
    number: "03",
    title: "Aparta tu fecha",
    description: "Agenda tu prueba y asegura el vestido para tu evento.",
  },
  {
    number: "04",
    title: "Luce espectacular",
    description: "Recibe tu vestido listo para hacer de tu noche algo único.",
  },
];

export const DRESSES: Dress[] = [
  {
    id: "rojo-1",
    name: "Rojo intenso",
    price: 850,
    sizes: ["CH", "M"],
    color: "champagne",
    imageUrl: "/images/dresses/1.webp",
    category: DressCategory.EVENING,
    isAvailable: true,
  },
  {
    id: "oro-rosa",
    name: "Oro rosa",
    price: 850,
    sizes: ["M", "G"],
    color: "verde esmeralda",
    imageUrl: "/images/dresses/2.webp",
    category: DressCategory.GRADUATION,
    isAvailable: true,
  },
  {
    id: "negro-cuero",
    name: "Negro cuero",
    price: 850,
    sizes: ["XS", "CH", "M"],
    color: "rosa empolvado",
    imageUrl: "/images/dresses/3.webp",
    category: DressCategory.QUINCEANERA,
    isAvailable: true,
  },
  {
    id: "purpura-bizantino",
    name: "Púrpura bizantino",
    price: 850,
    sizes: ["M", "G", "XG"],
    color: "negro",
    imageUrl: "/images/dresses/4.webp",
    category: DressCategory.EVENING,
    isAvailable: true,
  },
  {
    id: "azul-crepusculo",
    name: "Azul Crepúsculo",
    price: 850,
    sizes: ["CH", "M"],
    color: "marfil",
    imageUrl: "/images/dresses/5.webp",
    category: DressCategory.WEDDING,
    isAvailable: true,
  },
  {
    id: "cuarzo-rosa",
    name: "Cuarzo rosa",
    price: 850,
    sizes: ["CH", "M", "G"],
    color: "rojo vino",
    imageUrl: "/images/dresses/6.webp",
    category: DressCategory.GRADUATION,
    isAvailable: true,
  },
  {
    id: "luna-cristal",
    name: "Luna de cristal",
    price: 950,
    sizes: ["XS", "CH", "M"],
    color: "blanco perla",
    imageUrl: "/images/dresses/7.webp",
    category: DressCategory.EVENING,
    isAvailable: true,
  },
  {
    id: "aurora-boreal",
    name: "Aurora boreal",
    price: 1200,
    sizes: ["CH", "M", "G"],
    color: "azul cielo",
    imageUrl: "/images/dresses/8.webp",
    category: DressCategory.WEDDING,
    isAvailable: true,
  },
  {
    id: "sueno-dorado",
    name: "Sueño dorado",
    price: 850,
    sizes: ["M", "G", "XG"],
    color: "dorado",
    imageUrl: "/images/dresses/9.webp",
    category: DressCategory.QUINCEANERA,
    isAvailable: true,
  },
  {
    id: "rosa-salvaje",
    name: "Rosa salvaje",
    price: 780,
    sizes: ["XS", "CH"],
    color: "rosa intenso",
    imageUrl: "/images/dresses/10.webp",
    category: DressCategory.EVENING,
    isAvailable: true,
  },
  {
    id: "mariposa-negra",
    name: "Mariposa negra",
    price: 700,
    sizes: ["CH", "M", "G"],
    color: "negro",
    imageUrl: "/images/dresses/11.webp",
    category: DressCategory.GRADUATION,
    isAvailable: true,
  },
  {
    id: "diamante-azul",
    name: "Diamante azul",
    price: 1350,
    sizes: ["XS", "CH", "M"],
    color: "azul marino",
    imageUrl: "/images/dresses/12.webp",
    category: DressCategory.WEDDING,
    isAvailable: true,
  },
  {
    id: "vino-tinto",
    name: "Vino tinto",
    price: 900,
    sizes: ["M", "G"],
    color: "burdeos",
    imageUrl: "/images/dresses/13.webp",
    category: DressCategory.EVENING,
    isAvailable: true,
  },
  {
    id: "perla-oriente",
    name: "Perla del oriente",
    price: 950,
    sizes: ["CH", "M", "G"],
    color: "marfil",
    imageUrl: "/images/dresses/14.webp",
    category: DressCategory.QUINCEANERA,
    isAvailable: true,
  },
  {
    id: "ebano-marfil",
    name: "Ébano y marfil",
    price: 1100,
    sizes: ["XS", "CH", "M", "G"],
    color: "negro y blanco",
    imageUrl: "/images/dresses/15.webp",
    category: DressCategory.EVENING,
    isAvailable: true,
  },
  {
    id: "jazmin-eterno",
    name: "Jazmín eterno",
    price: 750,
    sizes: ["CH", "M"],
    color: "blanco",
    imageUrl: "/images/dresses/16.webp",
    category: DressCategory.GRADUATION,
    isAvailable: true,
  },
  {
    id: "crepusculo-violeta",
    name: "Crepúsculo violeta",
    price: 880,
    sizes: ["M", "G", "XG"],
    color: "violeta",
    imageUrl: "/images/dresses/17.webp",
    category: DressCategory.EVENING,
    isAvailable: true,
  },
  {
    id: "sol-invierno",
    name: "Sol de invierno",
    price: 1250,
    sizes: ["XS", "CH", "M"],
    color: "champagne",
    imageUrl: "/images/dresses/18.webp",
    category: DressCategory.WEDDING,
    isAvailable: true,
  },
  {
    id: "fuego-sagrado",
    name: "Fuego sagrado",
    price: 920,
    sizes: ["CH", "M", "G"],
    color: "rojo fuego",
    imageUrl: "/images/dresses/19.webp",
    category: DressCategory.QUINCEANERA,
    isAvailable: true,
  },
  {
    id: "seda-nubes",
    name: "Seda y nubes",
    price: 980,
    sizes: ["XS", "CH", "M"],
    color: "blanco hielo",
    imageUrl: "/images/dresses/20.webp",
    category: DressCategory.EVENING,
    isAvailable: true,
  },
  {
    id: "estrella-fugaz",
    name: "Estrella fugaz",
    price: 720,
    sizes: ["CH", "M"],
    color: "plata",
    imageUrl: "/images/dresses/21.webp",
    category: DressCategory.GRADUATION,
    isAvailable: true,
  },
  {
    id: "reina-hielo",
    name: "Reina de hielo",
    price: 1400,
    sizes: ["XS", "CH", "M", "G"],
    color: "azul hielo",
    imageUrl: "/images/dresses/22.webp",
    category: DressCategory.WEDDING,
    isAvailable: true,
  },
  {
    id: "menta-fresca",
    name: "Menta fresca",
    price: 830,
    sizes: ["CH", "M", "G"],
    color: "verde menta",
    imageUrl: "/images/dresses/23.webp",
    category: DressCategory.EVENING,
    isAvailable: true,
  },
  {
    id: "trigo-maduro",
    name: "Trigo maduro",
    price: 680,
    sizes: ["M", "G"],
    color: "beige",
    imageUrl: "/images/dresses/24.webp",
    category: DressCategory.GRADUATION,
    isAvailable: true,
  },
  {
    id: "carmin-eterno",
    name: "Carmín eterno",
    price: 870,
    sizes: ["XS", "CH", "M"],
    color: "carmin",
    imageUrl: "/images/dresses/25.webp",
    category: DressCategory.EVENING,
    isAvailable: true,
  },
  {
    id: "plata-lunar",
    name: "Plata lunar",
    price: 960,
    sizes: ["CH", "M", "G", "XG"],
    color: "gris plata",
    imageUrl: "/images/dresses/26.webp",
    category: DressCategory.QUINCEANERA,
    isAvailable: true,
  },
  {
    id: "brisa-mar",
    name: "Brisa del mar",
    price: 1150,
    sizes: ["XS", "CH", "M"],
    color: "turquesa",
    imageUrl: "/images/dresses/27.webp",
    category: DressCategory.WEDDING,
    isAvailable: true,
  },
  {
    id: "sombra-dorada",
    name: "Sombra dorada",
    price: 910,
    sizes: ["M", "G"],
    color: "dorado viejo",
    imageUrl: "/images/dresses/28.webp",
    category: DressCategory.EVENING,
    isAvailable: true,
  },
  {
    id: "amatista-real",
    name: "Amatista real",
    price: 990,
    sizes: ["CH", "M", "G"],
    color: "lila",
    imageUrl: "/images/dresses/29.webp",
    category: DressCategory.QUINCEANERA,
    isAvailable: true,
  },
  {
    id: "ultimo-suspiro",
    name: "Último suspiro",
    price: 1050,
    sizes: ["XS", "CH", "M"],
    color: "rosa gold",
    imageUrl: "/images/dresses/30.webp",
    category: DressCategory.EVENING,
    isAvailable: true,
  },
];
