import { DressCategory, ServiceIcon } from "@/types";

import type { Dress, ProcessStep, Service } from "@/types";

export const SERVICES: Service[] = [
  {
    title: "Renta de vestidos",
    description:
      "Diseños inolvidables para tu evento, sin comprometer tu presupuesto.",
    icon: ServiceIcon.SPARKLES,
  },
  {
    title: "Venta de vestidos",
    description:
      "Encuentra esa pieza especial que querrás conservar para siempre.",
    icon: ServiceIcon.SHOPPING_BAG,
  },
  {
    title: "Asesoría personalizada",
    description:
      "Te ayudamos a elegir el corte, color y talla que mejor realzan tu estilo.",
    icon: ServiceIcon.HEART_HANDSHAKE,
  },
];

export const PROCESS_STEPS: ProcessStep[] = [
  {
    number: "01",
    title: "Elige tu vestido",
    description: "Explora nuestros estilos y guarda tus favoritos.",
  },
  {
    number: "02",
    title: "Escríbenos",
    description: "Confirma disponibilidad y recibe asesoría por WhatsApp.",
  },
  {
    number: "03",
    title: "Aparta tu fecha",
    description: "Agenda tu prueba y asegura el vestido para tu evento.",
  },
  {
    number: "04",
    title: "Luce espectacular",
    description: "Recibe tu vestido listo para hacer de tu noche algo único.",
  },
];

export const DRESSES: Dress[] = [
  {
    id: "1",
    name: "Rojo intenso",
    price: 850,
    sizes: [],
    color: ["rojo"],
    colorHex: "#D01B30",
    imageUrl: "/images/dresses/1.webp",
    category: DressCategory.EVENING,
    isAvailable: true,
  },
  {
    id: "2",
    name: "Oro rosa",
    price: 900,
    sizes: ["6"],
    color: ["rosa"],
    colorHex: "#EFDCDE",
    imageUrl: "/images/dresses/2.webp",
    backImageUrl: "/images/dresses/2-b.webp",
    category: DressCategory.GRADUATION,
    isAvailable: true,
    imageScale: 1.07,
  },
  {
    id: "3",
    name: "Negro cuero",
    price: 800,
    sizes: ["6"],
    color: ["negro"],
    colorHex: "#201E1A",
    imageUrl: "/images/dresses/3.webp",
    category: DressCategory.QUINCEANERA,
    isAvailable: true,
  },
  {
    id: "4",
    name: "Púrpura bizantino",
    price: 900,
    sizes: ["4"],
    color: ["púrpura"],
    colorHex: "#9F3383",
    imageUrl: "/images/dresses/4.webp",
    category: DressCategory.EVENING,
    isAvailable: true,
    imageScale: 1.13,
  },
  {
    id: "5",
    name: "Azul Crepúsculo",
    price: 900,
    sizes: ["4"],
    color: ["azul"],
    colorHex: "#102F3D",
    imageUrl: "/images/dresses/5.webp",
    category: DressCategory.WEDDING,
    isAvailable: true,
    imageScale: 1.25,
  },
  {
    id: "6",
    name: "Cuarzo rosa",
    price: 900,
    sizes: ["6"],
    color: ["rosa"],
    colorHex: "#F3C9C3",
    imageUrl: "/images/dresses/6.webp",
    category: DressCategory.GRADUATION,
    isAvailable: true,
    imageScale: 1.11,
  },
  {
    id: "7",
    name: "Negro obsidiana",
    price: 1000,
    sizes: ["5/6"],
    color: ["negro"],
    colorHex: "#0E0D12",
    imageUrl: "/images/dresses/7.webp",
    category: DressCategory.EVENING,
    isAvailable: true,
    imageScale: 1.1,
  },
  {
    id: "8",
    name: "Azul petróleo",
    price: 900,
    sizes: ["10"],
    color: ["azul cielo"],
    colorHex: "#045D90",
    imageUrl: "/images/dresses/8.webp",
    category: DressCategory.WEDDING,
    isAvailable: true,
    imageScale: 1.08,
  },
  {
    id: "9",
    name: "Rojo fresa",
    price: 1000,
    sizes: ["6"],
    color: ["rojo"],
    colorHex: "#FB2B3D",
    imageUrl: "/images/dresses/9.webp",
    category: DressCategory.QUINCEANERA,
    isAvailable: true,
    imageScale: 1.18,
  },
  {
    id: "10",
    name: "Negro",
    price: 1000,
    sizes: ["9/10"],
    color: ["negro"],
    colorHex: "#272429",
    imageUrl: "/images/dresses/10.webp",
    category: DressCategory.EVENING,
    isAvailable: true,
    imageScale: 1.13,
  },
  {
    id: "11",
    name: "Lila grisáceo",
    price: 1000,
    sizes: ["8"],
    color: ["gris"],
    colorHex: "#ACABBF",
    imageUrl: "/images/dresses/11.webp",
    category: DressCategory.GRADUATION,
    isAvailable: true,
    imageScale: 1.12,
  },
  {
    id: "12",
    name: "Floral multicolor",
    price: 900,
    sizes: ["10"],
    color: ["varios"],
    colorHex:
      "linear-gradient(135deg, #BA9248, #EEDBD1, #006C88, #C85071, #70369D)",
    imageUrl: "/images/dresses/12.webp",
    category: DressCategory.WEDDING,
    isAvailable: true,
    imageScale: 1.11,
  },
  {
    id: "13",
    name: "Fucsia",
    price: 900,
    sizes: ["12"],
    color: ["rosa"],
    colorHex: "#F03595",
    imageUrl: "/images/dresses/13.webp",
    category: DressCategory.EVENING,
    isAvailable: true,
    imageScale: 1.11,
  },
  {
    id: "14",
    name: "Cobré rosado",
    price: 900,
    sizes: ["M"],
    color: ["rosa"],
    colorHex: "#936152",
    imageUrl: "/images/dresses/14.webp",
    category: DressCategory.EVENING,
    isAvailable: true,
    imageScale: 1.23,
  },
  {
    id: "15",
    name: "Rosa empolvado",
    price: 1000,
    sizes: ["1"],
    color: ["rosa"],
    colorHex: "#D49AA0",
    imageUrl: "/images/dresses/15.webp",
    category: DressCategory.EVENING,
    isAvailable: true,
    imageScale: 1.11,
  },
  {
    id: "16",
    name: "Rojo navidad",
    price: 900,
    sizes: ["4"],
    color: ["rojo"],
    colorHex: "#C3001C",
    imageUrl: "/images/dresses/16.webp",
    backImageUrl: "/images/dresses/16-b.webp",
    category: DressCategory.EVENING,
    isAvailable: true,
    imageScale: 1.1,
  },
  {
    id: "17",
    name: "Rojo cereza",
    price: 800,
    sizes: ["3/4"],
    color: ["rojo"],
    colorHex: "#CC1335",
    imageUrl: "/images/dresses/17.webp",
    category: DressCategory.EVENING,
    isAvailable: true,
    imageScale: 1.1,
  },
  {
    id: "18",
    name: "Negro cálido",
    price: 1000,
    sizes: ["11"],
    color: ["negro"],
    colorHex: "#201C19",
    imageUrl: "/images/dresses/18.webp",
    backImageUrl: "/images/dresses/18-b.webp",
    category: DressCategory.EVENING,
    isAvailable: true,
    imageScale: 1.1,
  },
  {
    id: "19",
    name: "Verde salvia",
    price: 1000,
    sizes: ["3"],
    color: ["verde"],
    colorHex: "#97A99C",
    imageUrl: "/images/dresses/19.webp",
    category: DressCategory.EVENING,
    isAvailable: true,
    imageScale: 1.1,
  },
  {
    id: "20",
    name: "Negro",
    price: 900,
    sizes: ["10"],
    color: ["negro"],
    colorHex: "#0D0A10",
    imageUrl: "/images/dresses/20.webp",
    category: DressCategory.EVENING,
    isAvailable: true,
    imageScale: 1.25,
  },
  {
    id: "21",
    name: "Azul oscuro",
    price: 900,
    sizes: ["S"],
    color: ["azul"],
    colorHex: "#2B324F",
    imageUrl: "/images/dresses/21.webp",
    category: DressCategory.EVENING,
    isAvailable: true,
    imageScale: 1.23,
  },
  {
    id: "22",
    name: "Blanco plateado",
    price: 800,
    sizes: ["M"],
    color: ["blanco", "gris"],
    colorHex: "linear-gradient(135deg, #FDF9F8, #A59E9D)",
    imageUrl: "/images/dresses/22.webp",
    category: DressCategory.EVENING,
    isAvailable: true,
    imageScale: 1.22,
  },
  {
    id: "23",
    name: "Azul media noche",
    price: 900,
    sizes: ["4"],
    color: ["azul"],
    colorHex: "#1B1E32",
    imageUrl: "/images/dresses/23.webp",
    category: DressCategory.EVENING,
    isAvailable: true,
    imageScale: 1.25,
  },
  {
    id: "24",
    name: "Azul marino",
    price: 1000,
    sizes: ["5/6"],
    color: ["azul"],
    colorHex: "#1C1D74",
    imageUrl: "/images/dresses/24.webp",
    category: DressCategory.EVENING,
    isAvailable: true,
    imageScale: 1.24,
  },
  {
    id: "25",
    name: "Negro perla",
    price: 1000,
    sizes: ["10"],
    color: ["negro"],
    colorHex: "linear-gradient(135deg, #EDDDD8, #1A161E)",
    imageUrl: "/images/dresses/25.webp",
    category: DressCategory.EVENING,
    isAvailable: true,
    imageScale: 1.15,
  },
  {
    id: "26",
    name: "Marrón topo",
    price: 1000,
    sizes: ["4"],
    color: ["café"],
    colorHex: "#736658",
    imageUrl: "/images/dresses/26.webp",
    category: DressCategory.EVENING,
    isAvailable: true,
    imageScale: 1.12,
  },
  {
    id: "27",
    name: "Verde hierba",
    price: 1000,
    sizes: ["4"],
    color: ["verde"],
    colorHex: "#619E68",
    imageUrl: "/images/dresses/27.webp",
    category: DressCategory.EVENING,
    isAvailable: true,
    imageScale: 1.19,
  },
  {
    id: "28",
    name: "Marrón cobrizo",
    price: 900,
    sizes: ["10"],
    color: ["café"],
    colorHex: "#87573C",
    imageUrl: "/images/dresses/28.webp",
    backImageUrl: "/images/dresses/28-b.webp",
    category: DressCategory.EVENING,
    isAvailable: true,
    imageScale: 1.09,
  },
  {
    id: "29",
    name: "Perla rosa",
    price: 1000,
    sizes: ["3/4"],
    color: ["rosa"],
    colorHex: "linear-gradient(135deg, #EDDDD8, #A96C8A)",
    imageUrl: "/images/dresses/29.webp",
    category: DressCategory.EVENING,
    isAvailable: true,
    imageScale: 1.11,
  },
  {
    id: "30",
    name: "Beige grisáceo",
    price: 1000,
    sizes: ["S"],
    color: ["gris"],
    colorHex: "#C2B6AA",
    imageUrl: "/images/dresses/30.webp",
    category: DressCategory.EVENING,
    isAvailable: true,
    imageScale: 1.15,
  },
  {
    id: "31",
    name: "Cobre rosado",
    price: 1000,
    sizes: ["M"],
    color: ["café"],
    colorHex: "#C08A76",
    imageUrl: "/images/dresses/31.webp",
    category: DressCategory.EVENING,
    isAvailable: true,
    imageScale: 1.02,
  },
  {
    id: "32",
    name: "Azul iridiscente",
    price: 1000,
    sizes: ["S"],
    color: ["azul"],
    colorHex: "linear-gradient(135deg, #A19FD1, #C2C8E2)",
    imageUrl: "/images/dresses/32.webp",
    category: DressCategory.EVENING,
    isAvailable: true,
    imageScale: 1.05,
  },
  {
    id: "33",
    name: "Rosa pastel",
    price: 1000,
    sizes: ["3"],
    color: ["rosa"],
    colorHex: "#E1C5BC",
    imageUrl: "/images/dresses/33.webp",
    backImageUrl: "/images/dresses/33-b.webp",
    category: DressCategory.EVENING,
    isAvailable: true,
    imageScale: 1.21,
  },
  // aquí vamos
  {
    id: "34",
    name: "Azul polvo",
    price: 700,
    sizes: ["S"],
    color: ["azul"],
    colorHex: "#9CB1C9",
    imageUrl: "/images/dresses/34.webp",
    category: DressCategory.EVENING,
    isAvailable: true,
    imageScale: 1.07,
  },
  {
    id: "35",
    name: "Beige",
    price: 700,
    sizes: ["8"],
    color: ["amarillo"],
    colorHex: "#E7D9BB",
    imageUrl: "/images/dresses/35.webp",
    category: DressCategory.EVENING,
    isAvailable: true,
    imageScale: 1.08,
  },
  {
    id: "36",
    name: "Azul zafiro",
    price: 800,
    sizes: ["3"],
    color: ["azul"],
    colorHex: "#1752BC",
    imageUrl: "/images/dresses/36.webp",
    backImageUrl: "/images/dresses/36-b.webp",
    category: DressCategory.EVENING,
    isAvailable: true,
    imageScale: 1.25,
  },
  {
    id: "37",
    name: "Rojo vivo",
    price: 800,
    sizes: ["6"],
    color: ["rojo"],
    colorHex: "#D81635",
    imageUrl: "/images/dresses/37.webp",
    backImageUrl: "/images/dresses/37-b.webp",
    category: DressCategory.EVENING,
    isAvailable: true,
    imageScale: 1.11,
  },
  {
    id: "38",
    name: "Negro",
    price: 800,
    sizes: ["M"],
    color: ["negro"],
    colorHex: "#2C292A",
    imageUrl: "/images/dresses/38.webp",
    category: DressCategory.EVENING,
    isAvailable: true,
    imageScale: 1.08,
  },
  {
    id: "39",
    name: "Rojo frambuesa",
    price: 800,
    sizes: ["10"],
    color: ["rojo"],
    colorHex: "#AC2149",
    imageUrl: "/images/dresses/39.webp",
    backImageUrl: "/images/dresses/39-b.webp",
    category: DressCategory.EVENING,
    isAvailable: true,
    imageScale: 1.08,
  },
  {
    id: "40",
    name: "Blanco",
    price: 900,
    sizes: ["M"],
    color: ["blanco"],
    colorHex: "#F4F3EF",
    imageUrl: "/images/dresses/40.webp",
    backImageUrl: "/images/dresses/40-b.webp",
    category: DressCategory.EVENING,
    isAvailable: true,
    imageScale: 1.16,
  },
];
